### PR TITLE
feat: --tag-only flag

### LINKED ISSUE #101: feature: additional flags (--skip-commit-but-tag, --skip-csproj)
I have been looking at conventional commits for a while in the .NET space for a while.

I have an idea of how I'd like to implement it but the tools so far haven't had the option set I need, I think with a small set of additional options this library might be able to do what I need.

The idea is that I'd like to use git tags only to manage the versioning and keep the changelog.md files in a repo of it's own. The reason for this is to not have additional release commits in `main`  I'd simply like to trigger a release manually generate the file, push that to another repo and then tag the commit with the new version number via this tool.

In order to do this I'd like an option to skip the auto commit but still perform the git tag, it would also be nice to have to add the additional bits to the csproj, hence the two additional flags I am proposing.

Happy to start working on this is it's suitable for this project?

Thanks,
Billy

### PR DESCRIPTION
**Pull request by mumby0168**
Closes #101

### CODE REVIEW

**Comment by mumby0168** [comment]
> Thanks for the PR, mumby!
> 
> The current logic always uses the csproj version for bump logic, so unfortunately subsequent version bumps will be incorrect (since the csproj version updates don't get committed) unless the user always uses ReleaseAs. Here's an updated version of your test to demonstrate the failure.
> 
> ```cs
> public void ShouldSkipCommitButTagWhenConfigured()
> {
>     TempProject.CreateCsharpProject(Path.Join(_testSetup.WorkingDirectory, "project1"));
> 
>     CommitAll(_testSetup.Repository);
> 
>     var workingCopy = WorkingCopy.Discover(_testSetup.WorkingDirectory);
>     workingCopy.Versionize(new VersionizeOptions
>     {
>         ReleaseAs = "2.0.0",
>         SkipCommitButTag = true
>     });
> 
>     var projects = Projects.Discover(_testSetup.WorkingDirectory);
>     // Reset the csproj version to 1.0.0 to represent it not being committed.
>     projects.WriteVersion(SemanticVersion.Parse("1.0.0"));
>     var fileCommitter = new FileCommitter(_testSetup);
>     fileCommitter.CommitChange("fix: a fix");
>     workingCopy.Versionize(new VersionizeOptions
>     {
>         SkipCommitButTag = true
>     });
> 
>     _testSetup.Repository.Tags.Count().ShouldBe(2);
>     _testSetup.Repository.Tags.Select(t => t.FriendlyName).ShouldBe(new[] { "v2.0.0", "v2.0.1" }); // Fails here
>     _testSetup.Repository.Commits.Count().ShouldBe(2);
> }
> ```
> 
> So, we might have to add another flag arg to tell versionize to use tags to read the lastest version, instead.

Hi thanks for taking the time to review, so I have pushed a pre-release version with these changes in it and it seems to work great, where no commits are made back to the repo, I took the idea from this flag which seems to imply that by default that it uses tags rather than the .csproj version for the primary method for increment the version:

```
--proj-version-bump-logic            Use project version for bump logic, as opposed to git tag version.
```

See the example project that I've been playing with via an azure pipeline that certainly can't be committing the version as it does not have sufficient permissions:

image

I've also included my pipeline, just wondering whether I've missed some on the tests to reflect this working?

```yaml
trigger: none

stages:
- stage: release_notes
  displayName: conventional commit
  jobs:
  - job: versionize
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        fetchDepth: 0
        persistCredentials: "true"
        displayName: Checkout src repo

      - checkout: git://NewStartersAndPlacements/change-logs
        displayName: Checkout change log repo

      - task: UseDotNet@2
        displayName: .NET Setup
        inputs:
          packageType: 'sdk'
          version: '7.0.x'

      - script: |
          dotnet tool restore
        workingDirectory: $(Build.Repository.Name)
        displayName: Install Versionize

      - script: |
          cp logs/$(Build.Repository.Name)/CHANGELOG.md ../nsf-module-one-lewis-foot
        workingDirectory: change-logs
        displayName: Copy Repo Change Log

      - script: |
          git config --global user.email "$(Build.Repository.Name)@automated.com"
          git config --global user.name "$(Build.Repository.Name) - conventional commits"

          dotnet versionize --skip-commit-but-tag --skip-dirty  

          git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push --tags -f
        name: npm_bump_script
        displayName: Bump Version
        workingDirectory: $(Build.Repository.Name)

      - script: |
          cp $(Build.Repository.Name)/CHANGELOG.md change-logs/logs/$(Build.Repository.Name)
        displayName: Copy changelog back to source repo

      - script: |
          git config --global user.email "$(Build.Repository.Name)@automated.com"
          git config --global user.name "$(Build.Repository.Name) - conventional commits"

          git add ./logs/$(Build.Repository.Name)/CHANGELOG.md
          git commit -m "new release for $(Build.Repository.Name)"
          git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin HEAD:main
        workingDirectory: change-logs
        displayName: Push back change log
    
```

Thinking again, we could implement a flag, that skips the check for the .csproj version and doesn't make a commit and solely relies on git tags to meet this criteria.

Happy to be proven wrong, but I wonder if adding to the flag to skip the version file modification it may prove this out, as you can see I had to add the --skip-dirty flag as it does mess with the version in the .csproj file but I never choose to commit that back up, it's just done via the git tag.

Thanks again for assisting on this.

**Comment by cabauman** [comment]
<blockquote>
I took the idea from this flag which seems to imply that by default that it uses tags rather than the .csproj version for the primary method for increment the version:  

```
--proj-version-bump-logic            Use project version for bump logic, as opposed to git tag version.
```
</blockquote>

Yeah, you're right. There was apparently a misstep in the naming...

> Thinking again, we could implement a flag, that skips the check for the .csproj version and doesn't make a commit and solely relies on git tags to meet this criteria.

Yeah, modifying the logic to not read from or write to the csproj at all. There are numerous locations in the `Versionize` method where `projects.Version` is referenced (starting [here](projects.Version) that will need to be changed.

**Comment by mumby0168** [comment]
> Yeah, modifying the logic to not read from or write to the csproj at all. There are numerous locations in the `Versionize` method where `projects.Version` is referenced (starting [here](https://github.com/versionize/versionize/blob/b1cfb7c1a9b8c79f8dc2d305f7234a72e6dba183/Versionize/WorkingCopy.cs#L73)) that will need to be changed.

I'll take a look at this and get a flag that ignores both the .csproj file checks, logic bump and solely updates based on git tags, will update this PR once done, thanks again for your support.

**Comment by cabauman** [comment]
Great. Did a quick look-through, and looks good. I'm on holiday so I'll continue the review process when I get back.

**Comment by cabauman** [comment]
I like it. The only thing I might change is

```
else if (options.DryRun is false || options.TagOnly)
```
to
```
else if (options.DryRun is false && options.TagOnly)
```

to make it respect the dry run request (no tagging if DryRun is set to true). Thoughts?

**Comment by mumby0168** [comment]
Hi @cabauman thanks for the review, I have update the PR, good spots!

**Comment by cabauman** [comment]
Sorry for the delay, I'll get to it this week!

**Comment by cabauman** [comment]
Thanks for your contribution and patience throughout the review process!

**Comment by cabauman** [comment]
Never mind. I'll take care of it later. You've been patient.

**Pull request merged**
