### PR TITLE
chore: refactor towards mono repo support

### PR DESCRIPTION
**Pull request by saintedlama**

### CODE REVIEW

**Comment by aeb-dev** [comment]
What is the status of this?

**Comment by esteimanuel** [comment]
@saintedlama is this something that can be built upon or does it require redesign?

If it requires redesign what challenges did you have implementing your solution?

**Comment by Deadvi5** [comment]
Any update on this feature? it would be really nice to have also this option!

**Comment by cabauman** [comment]
Closing in favor of [monorepo support](https://github.com/versionize/versionize/commit/37a5cf96984dfe52cbf0b0a52889e6015bb405c7). Thanks for giving this a go!

**Pull request closed without merging**
