### PR TITLE
feat: Add first-parent commits option

### PR DESCRIPTION
**Pull request by RemiCELLARD**
- Add first-parent-commits options : The first parent only options allows you to ignore commits that are not the first parent.

See #139 

Work based on version 2 - See #135

### CODE REVIEW

**Comment by cabauman** [comment]
Nice. This is a config option I'll be using too.
And great test 💪

**Comment by RemiCELLARD** [comment]
Hi,

Thanks for your feedback.

I tried to reproduce the test case by adding a comment on merge. The library doesn't offer this feature.
We'll have to wait and see how this test is updated when LibGit2Sharp integrates this feature.

**Comment by cabauman** [comment]
Oh ok, so this feature doesn't work as expected yet?

**Comment by RemiCELLARD** [comment]
> Oh ok, so this feature doesn't work as expected yet?

The feature works properly. This is my test implementation, which is restricted by LibGit2Sharp.

In the versionize test, we want to check that the changelog only contains the merge message.
But ... you can't put a message in a merge with LibGit2Sharp.
So the versionize test verifies that we don't have the branch commit message but not the merge message.

**Comment by cabauman** [comment]
Ok, understood.

**Pull request merged**
