### PR TITLE
feat: add monorepo support

### PR DESCRIPTION
**Pull request by nigma143**

### CODE REVIEW

**Comment by cabauman** [comment]
Thanks @nigma143. Mind taking care of the merge conflicts?

**Comment by nigma143** [comment]
> Thanks @nigma143. Mind taking care of the merge conflicts?

done

**Comment by cabauman** [comment]
I think you'll need to rebase on master. All conflicts seem to be trivial except in Program.cs:

Screenshot 2024-04-29 150656

**Comment by nigma143** [comment]
done
@cabauman

**Pull request merged**
